---
- name: "Removing Old {{ item.name }} pack"
  shell: "st2 pack remove {{ item.name }}"

- name: "Installing {{ item.name }} pack from Stackstorm Exchange"
  shell: "st2 pack install {{ item.name }}"
  when: item.repo is undefined or item.repo == ""

- name: "Installing {{ item.name }} pack from Git"
  shell: "st2 pack install {{ item.repo }}"
  when: item.repo is defined and item.repo != ""